FROM oven/bun:1.2.2

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json    
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./.npmrc ./.npmrc
COPY ./apps/web ./apps/web

RUN bun install

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]